export const eventsDummy = [
  {
    id: 1,
    category: "all",
    title: "JCC Regional 1",
    description: "Perlombaan akademik TK, SD dan SMP di SMAN 1 Pesanggaran",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: true,
  },
  {
    id: 2,
    category: "all",
    title: "JCC Regional 2",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 3,
    category: "all",
    title: "JCC Regional 3",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 4,
    category: "all",
    title: "JCC Regional 4",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 5,
    category: "all",
    title: "JCC Regional 5",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 6,
    category: "all",
    title: "JCC Regional 6",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 7,
    category: "all",
    title: "JCC Regional 7",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 8,
    category: "all",
    title: "JCC Regional 8",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 9,
    category: "all",
    title: "JCC Regional 9",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 10,
    category: "all",
    title: "JCC Regional 10",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 2,
    category: "all",
    title: "JCC Regional 2",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 3,
    category: "all",
    title: "JCC Regional 3",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 4,
    category: "all",
    title: "JCC Regional 4",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 5,
    category: "all",
    title: "JCC Regional 5",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 6,
    category: "all",
    title: "JCC Regional 6",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 7,
    category: "all",
    title: "JCC Regional 7",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 8,
    category: "all",
    title: "JCC Regional 8",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 9,
    category: "all",
    title: "JCC Regional 9",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
  {
    id: 10,
    category: "all",
    title: "JCC Regional 10",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: "23 Feb 2025",
    time: "07.00 - 15.00 WIB",
    color: "bg-red-500",
    status: false,
  },
];
